# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e95f063260a2ee2ebae6e74eb20f8a7e529afecdca605934e8bcda274953236ba1db19321a168d8d66be3fc382ded69a2dee801665a4f79907693202d96d2e80

test:
  secret_key_base: 2244dc92d5cf69d033bba8dd5174e539b630c898c5a072cc0bc3250b27450cc9378a5e1b7dcf7c277abde53d8e325bb7a06ce786d4c9de8909dcfe009a2fa608

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
